# Noah Delano Weekly Check-In 11 November 18

### Problem I Am Proud Of

For the problem I am proud of, I decided to tackle a word problem, such that I had to figure out the system of equations myself and use Gaussian Elimination to find the answer. So below I find a fun one that took me a little time to figure out the system I need to use.

Problem: Ava invests a total of $\$ 10,000$  in three accounts, one paying  5  interest, another paying  8  interest, and the third paying  9  interest. The annual interest earned on the three investments last year was  $\$770$ . The amount invested at  9  was twice the amount invested at  5 . How much was invested at each rate?

First off, we know there are three seperate accounts that contributed to the total sum of money. So we can create our first equation with each account as a seperate variable:

$$x_1+x_2+x_3=10000$$

Since we don't know how much each contributed, we can't really include any coefficients. Next we look at the interest, where each investor has a different paying rate, which include $5$%, $8$%, and $9$%, coming to a total of $\$770$ between the three investors the previous years. So,

$$0.05x_1+0.08x_2+0.09x_3=770$$

Next we know the the investor who has a $9$% interest has the twice the amount invested compared to the investor with a $5$% interest. So:

$$2x_1-x_3=0$$

which is true because they would cancel each other out. Know we have a system of equations we can work with. Therefore we have:

$$E_1\rightarrow x_1+x_2+x_3=10000$$
$$E_2\rightarrow 0.05x_1+0.08x_2+0.09x_3=770$$
$$E_3\rightarrow 2x_1+0x_3-x_3=0$$

or rather:

$$\begin{bmatrix} 1&1&1\\0.05&0.08&0.09\\2&0&-1\\ \end{bmatrix}\begin{bmatrix} x_1\\x_2\\x_3\\ \end{bmatrix}=\begin{bmatrix} 10000\\770\\0\\ \end{bmatrix}$$

Lets start by eliminating $x_1$ from $E_2$ and $E_3$:

$$\begin{bmatrix} 1&1&1\\0.05&0.08&0.09\\2&0&-1\\ \end{bmatrix}\begin{bmatrix} x_1\\x_2\\x_3\\ \end{bmatrix}=\begin{bmatrix} 10000\\770\\0\\ \end{bmatrix}$$

$$\begin{bmatrix} 1&1&1\\1&1.6&1.8\\1&0&-\frac{1}{2}\\ \end{bmatrix}\begin{bmatrix} x_1\\x_2\\x_3\\ \end{bmatrix}=\begin{bmatrix} 10000\\15400\\0\\ \end{bmatrix}$$

So:

$$E_2-E_1\rightarrow 0.6x_2+0.8x_3=5400$$

$$E_3-E_1\rightarrow -x_2-\frac{3}{2}x_3=-10000\rightarrow x_2+\frac{3}{2}x_3=10000$$

In Matrix form:

$$\begin{bmatrix} 1&1&1\\0&0.6&0.8\\0&1&\frac{3}{2}\\ \end{bmatrix}\begin{bmatrix} x_1\\x_2\\x_3\\ \end{bmatrix}=\begin{bmatrix} 10000\\5400\\10000\\ \end{bmatrix}$$

$$\begin{bmatrix} 1&1&1\\0&\frac{3}{5}&\frac{4}{5}\\0&1&\frac{3}{2}\\ \end{bmatrix}\begin{bmatrix} x_1\\x_2\\x_3\\ \end{bmatrix}=\begin{bmatrix} 10000\\5400\\10000\\ \end{bmatrix}$$

$$\begin{bmatrix} 1&1&1\\0&1&\frac{4}{3}\\0&1&\frac{3}{2}\\ \end{bmatrix}\begin{bmatrix} x_1\\x_2\\x_3\\ \end{bmatrix}=\begin{bmatrix} 10000\\9000\\10000\\ \end{bmatrix}$$

Now to eliminate $x_2$ from $E_3$:

$$E_3-E_2\rightarrow \frac{1}{6}x_3=1000$$

In matrix form:

$$\begin{bmatrix} 1&1&1\\0&1&\frac{4}{3}\\0&0&\frac{1}{6}\\ \end{bmatrix}\begin{bmatrix} x_1\\x_2\\x_3\\ \end{bmatrix}=\begin{bmatrix} 10000\\9000\\1000\\ \end{bmatrix}$$

$$\begin{bmatrix} 1&1&1\\0&1&\frac{4}{3}\\0&0&1\\ \end{bmatrix}\begin{bmatrix} x_1\\x_2\\x_3\\ \end{bmatrix}=\begin{bmatrix} 10000\\9000\\6000\\ \end{bmatrix}$$

Now to Solve:

$$x_3=6000$$

Then:

$$x_2+\frac{4}{3}x_3=9000$$

$$x_2+8000=9000$$

$$x_2=1000$$

Finally:

$$x_1+x_2+x_3=10000$$

$$x_1+1000+6000=10000$$

$$x_1+7000=10000$$

$$x_1=3000$$

Therefore, investor $x_1$ invested $\$3000$ at a $5$% interest rate, investor $x_2$ invested $\$1000$ at a $8$% interest rate, and investor $x_3$ invested $\$6000$ at a $9$% interest rate

### Problem I Struggled With

For the problem I struggled with, I wanted to show off an anomally that kind of caught me off guard as it differe from some of the context given by the book.

It starts out with a simple system of equations that requires us to use Gaussian elimination. In Matrix form, the system is:

$$\begin{bmatrix} 5&3&9\\0-2&3&-1\\-1&-2&1\\ \end{bmatrix}\begin{bmatrix} x_1\\x_2\\x_3\\ \end{bmatrix}=\begin{bmatrix} 45\\1.751\\9\\ \end{bmatrix}$$

So I decided to incorporate professor Bieri's algorith for Gauss in order to solve this system:

In [7]:
#My imports
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
pd.set_option("display.max_rows", None, "display.max_columns", None)

In [8]:
#Basically copied this from the notes 
def gaussian_elim(A,b,show_work=False):
    
    # Get matrix sizes
    n,m = A.shape
    l = len(b)

    # Check matrix shapes
    if n != m:
        print('A matrix is not square')
        return 0
    if m != l:
        print('Rows in b do not match columns in A')
        return 0
    
    # Check for unique solution
    if np.linalg.det(A) == 0:
        print('Determinate of A is zero --> singular matrix')
        return 0
    
    if show_work == True:
        print('A matrix')
        print(A)
        print('------------------------')
        
    piv = np.arange(0,n) # pivot rows start in order
    for i in range (n-1):

        # PIVOTING
        index = np.argmax(np.abs(A[i:n,i])) # max for the subset of rows A[i:n,i]
        index = index + (i) # max for the full set of n rows

        if index != i:
            # then we need to pivot so the max element is in the top row
            temp_A = A[i,i:n].copy()
            A[i,i:n]=A[index,i:n]
            A[index,i:n]=temp_A

            temp_b = b[i].copy()
            b[i] = b[index]
            b[index] = temp_b

            temp_piv = piv[i].copy()
            piv[i] = piv[index]
            piv[index] = temp_piv
            
        if show_work == True:
            print('Pivot number', i+1)
            print(A)
            print('------------------------')

        # ELIMINATION
        A[i+1:n,i] = 1/A[i,i]*A[i+1:n,i] # multipliers
        for j in range(i+1,n):
            A[j,i+1:n] = A[j,i+1:n] - A[j,i]*A[i,i+1:n] # row operations on A
        b[i+1:n] = b[i+1:n] - A[i+1:n,i]*b[i] # row operations on b

        # REPLACE ZEROS - just so the matrix looks nice
        A[i+1:n,i] = np.zeros_like(A[i+1:n,i])
        if show_work == True:
            print('Row Operations number', i+1)
            print(A)
            print('------------------------')

    # SOLVE
    x = np.zeros_like(b)
    x[n-1]=b[n-1]/A[n-1,n-1]
    for i in reversed(range(0,n-1)):
        x[i] = (b[i] - np.matmul(A[i,i+1:n],x[i+1:n]))/A[i,i]


    ans = np.zeros_like(b)
    for i in piv:
        ans[i] = x[i]
        
    
    # REPORT RESULTS
    print('Final Results:')
    for i,xval in enumerate(ans):
        print('X{0} = {1:{digits}f}'.format(i,xval,digits=1))
        
    
    return ans

In [9]:
#Here are my matrices for the context of the problem, where it is our job to find the x values
A = np.array([(5,3,9),(-2,3,-1),(-1,-2,1)], dtype=float)
b = np.array([45,1.751,9], dtype=float)

x = gaussian_elim(A,b,True)

A matrix
[[ 5.  3.  9.]
 [-2.  3. -1.]
 [-1. -2.  1.]]
------------------------
Pivot number 1
[[ 5.  3.  9.]
 [-2.  3. -1.]
 [-1. -2.  1.]]
------------------------
Row Operations number 1
[[ 5.   3.   9. ]
 [ 0.   4.2  2.6]
 [ 0.  -1.4  2.8]]
------------------------
Pivot number 2
[[ 5.   3.   9. ]
 [ 0.   4.2  2.6]
 [ 0.  -1.4  2.8]]
------------------------
Row Operations number 2
[[5.         3.         9.        ]
 [0.         4.2        2.6       ]
 [0.         0.         3.66666667]]
------------------------
Final Results:
X0 = -3.399623
X1 = 0.552130
X2 = 6.704636


Now that makees sense for the most part. Then I decided to see what the answer is based on using pythons inverse function:

In [10]:
AINV = np.linalg.inv(A)
x1 = np.matmul(AINV, b)
print(x1)

[-3.39962338  0.55212987  6.70463636]


It may not be noticeable, but there is definetly some rounding error when it comes to the true answer solved through matrix inverse. Now this isn't what concerns me. I decided to try and write another defintion using gaussian elimination, but without pivoting. This is what happens:

In [11]:
def gauss_without_pivots(A, b):
    
    n = A.shape[0]

    #forward substitution, such that equations match for elimination
    for row in range(0, n-1):
        for i in range(row+1, n):
            factor = A[i,row] / A[row,row]#Match leading coefficient with first equation to get rid of variable
            for j in range(row, n):
                A[i,j] = A[i,j] - factor * A[row,j] #Apply factor to the whole equation

            b[i] = b[i] - factor * b[row]
        print('A = \n%s and b = %s' % (A,b))
     
    #Elimination
    x = np.zeros((n,1))
    x[n-1] = b[n-1] / A[n-1, n-1]
    for row in range(n-2, -1, -1):
        sums = b[row]
        for j in range(row+1, n):
            sums = sums - A[row,j] * x[j]
        x[row] = sums / A[row,row]
        
    return x

In [12]:
x = gauss_without_pivots(A,b)
print('Gauss result is x = \n %s' % x)

A = 
[[5.         3.         9.        ]
 [0.         4.2        2.6       ]
 [0.         0.         3.66666667]] and b = [45.         19.751      24.58366667]
A = 
[[5.         3.         9.        ]
 [0.         4.2        2.6       ]
 [0.         0.         3.66666667]] and b = [45.         19.751      24.58366667]
Gauss result is x = 
 [[-3.39962338]
 [ 0.55212987]
 [ 6.70463636]]


In this case, it got the answer exactly correct, and yet it used no pivoting. So my confusion is mostly in the purpose of pivots i guess. I though pivoting helped in preventing any sort of rounding error, but yet in this case, pivots created and error value. Don't know where to go from here.

### How I Contributed To My Group

Going to be totally honest, but I don't think I contributed too much with my group work this week. The content we have been going over has come very easy to me as it is basically a throwback to linear algebra, which I am sure a lot of people remeber bits and pieces of. And it wasn't just me who was quiet. My whole group was pretty quiet as we really had little to no questions that realy challenged us to engage in a tough discussion, which i think is a shame. However, on Monday Avi talked with us for a bit about some programs he wrote and posted involving matrices. He went through the deifferent features of work, which he said he got through pretty quick, but only took a long time bacause he added all the color and design elements, which I thought was pretty funny. Othere than that, this week was a bit dull for our group.

### Goals For Next Week

From the previous section, I said group discussions wer a bit dull, and seems like that has been happening, especially for me lately. Ever since changing groups, it just seems like I don't have the motivation to really engage in some conversations about the topics we learned. Really all I did was tended to talk about unrelated things, which is counter-productive. I was doing so good a while back, so I really need to get back to how I was. I need to be fully prepared, and make sure to list any questions I have. I have to try and figure out ways of using group time much more productively. Hence, increasing productivity in group time is my goal for next week.